[theme]
base = "dark"
primaryColor = "#6cddf5"
backgroundColor = "#090f1e"
secondaryBackgroundColor = "#14223a"
textColor = "#eaf2ff"
font = "sans serif"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
